Gestor.MVC/Controllers/AdministracionController.cs
using Gestor.MVC.Models;
using OLIMPIADAS.Dominio.DTO.Sedes;
using OLIMPIADAS.Servicios.Aplicacion.General;
using OLIMPIADAS.Servicios.Aplicacion.Intranet;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Gestor.MVC.Controllers
{
    public class AdministracionController : BaseController
    {
        //
        // GET: /Administracion/
        public ActionResult Index()
        {
            return View();
        }

        #region Sedes

        /// <summary>
        /// Vista Sedes
        /// </summary>
        /// <returns></returns>
        public ActionResult Sedes()
        {
            if (!this.IsValidSesion) return this.RedirectToLogin();
            var model = new Objetos() { Pageview = int.Parse(ConfigurationManager.AppSettings[ConstantesAppServicio.Pageview].ToString()) };

            return View(model);
        }
        public async Task<JsonResult> GetListaSedes()
        {
            var model = new Objetos();
            model.Count = 1;
            var datos = await (new OlimpiadasServicios()).GetSedes();
            model.ListaEstados = (List<EstadosDTO>)Session[DatosSesion.SesionEstados];
            model.Htmlview = ListaSedesHtml(datos);
            var json = Json(model, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = 1073741824;
            return json;
        }
        private string ListaSedesHtml(List<SedesDTO> lista)
        {
            StringBuilder strHtml = new StringBuilder();
            string siteRoot = ConfigurationManager.AppSettings[ConstantesAppServicio.InitialUrl].ToString();

            //***************************      CABECERA DE LA TABLA         ***********************************//
            strHtml.Append("");
            strHtml.Append(@"");
            strHtml.Append("<table class='table table-striped table-bordered table-hover dataTables-example'>");

            #region cabecera

            strHtml.Append("<thead>");

            strHtml.Append("<tr>");
            strHtml.Append("<th>&nbsp;</th>");
            strHtml.Append("<th>Sedes</th>");
            strHtml.Append("<th>Estado</th>");
            strHtml.Append("</tr>");

            strHtml.Append("</thead>");

            #endregion

            if (lista != null)
            {
                #region detalle

                strHtml.Append("<tbody>");

                foreach (var d in lista)
                {
                    strHtml.Append("<tr>");

                    strHtml.Append("<td style='text-align:center'>");
                    strHtml.Append("<a href='#' onclick=\"edit_('" + d.IdSede + "','" + d.SedeDes + "','" + d.IdEstado + "');\">");
                    strHtml.Append("<img src='" + siteRoot + "/Contenido/Images/btn-edit.png' /></a>&nbsp;");
                    strHtml.Append("<a href='#' onclick=\"delete_('" + d.IdSede + "');\">");
                    strHtml.Append("<img src='" + siteRoot + "/Contenido/Images/btn-cancel.png' /></a>");
                    strHtml.Append("</td>");
                    strHtml.Append("<td>" + d.SedeDes + "</td>");
                    strHtml.Append("<td>" + d.EstadoDes + "</td>");

                    strHtml.Append("</tr>");
                }

                strHtml.Append("</tbody>");
                #endregion
            }
            strHtml.Append("</table>");

            return strHtml.ToString();
        }
        public async Task<JsonResult> SaveSede(int id, string sede, int estado)
        {
            var obj = new SedesDTO()
            {
                IdSede = id,
                SedeDes = sede,
                IdEstado = estado
            };
            var json = new JsonResult();
            try
            {
                var datos = await new OlimpiadasServicios().UpdateSede(obj);

                var model = new Objetos();
                model.Count = 1;
                model.ListaEstados = (List<EstadosDTO>)Session[DatosSesion.SesionEstados];
                model.Htmlview = ListaSedesHtml(datos);
                json = Json(model);
            }
            catch (Exception ex)
            {
            }

            return json;
        }
        public async Task<JsonResult> DeleteSede(int id)
        {
            var json = new JsonResult();
            try
            {
                var datos = await new OlimpiadasServicios().DeleteSede(id);

                var model = new Objetos();
                model.Count = 1;
                model.ListaEstados = (List<EstadosDTO>)Session[DatosSesion.SesionEstados];
                model.Htmlview = ListaSedesHtml(datos);
                json = Json(model);
            }
            catch (Exception ex)
            {
            }

            return json;
        }

        #endregion

        #region ComplejoDeportivo

        /// <summary>
        /// Vista Complejos deportivos
        /// </summary>
        /// <returns></returns>
        public ActionResult ComplejoDeportivo()
        {
            if (!this.IsValidSesion) return this.RedirectToLogin();
            var model = new Objetos() { Pageview = int.Parse(ConfigurationManager.AppSettings[ConstantesAppServicio.Pageview].ToString()) };

            return View(model);
        }
        public async Task<JsonResult> GetListaComplejos()
        {
            var model = new Objetos();
            model.Count = 1;
            var datos = await (new OlimpiadasServicios()).GetListaComplejos();
            model.ListaSedes = await (new OlimpiadasServicios()).GetSedes();
            model.ListaTipoComplejosDeportivos = await (new OlimpiadasServicios()).GetTipoComplejosDeportivos();
            model.ListaEstados = (List<EstadosDTO>)Session[DatosSesion.SesionEstados];
            model.Htmlview = ListaComplejosHtml(datos);
            var json = Json(model, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = 1073741824;
            return json;
        }
        private string ListaComplejosHtml(List<ComplejoDeportivoAdiDTO> lista)
        {
            StringBuilder strHtml = new StringBuilder();
            string siteRoot = ConfigurationManager.AppSettings[ConstantesAppServicio.InitialUrl].ToString();

            //***************************      CABECERA DE LA TABLA         ***********************************//
            strHtml.Append("");
            strHtml.Append(@"");
            strHtml.Append("<table class='table table-striped table-bordered table-hover dataTables-example'>");

            #region cabecera

            strHtml.Append("<thead>");

            strHtml.Append("<tr>");
            strHtml.Append("<th>&nbsp;</th>");
            strHtml.Append("<th>Complejo Deportivo</th>");
            strHtml.Append("<th>Sede</th>");
            strHtml.Append("<th>Tipo</th>");
            strHtml.Append("<th>Estado</th>");
            strHtml.Append("</tr>");

            strHtml.Append("</thead>");

            #endregion

            if (lista != null)
            {
                #region detalle

                strHtml.Append("<tbody>");

                foreach (var d in lista)
                {
                    strHtml.Append("<tr>");

                    strHtml.Append("<td style='text-align:center'>");
                    strHtml.Append("<a href='#' onclick=\"edit_('" + d.IdComplejoDeportivo + "','" + d.ComplejoDeportivoDes + "','" + d.IdSede + "','" + d.IdTipoComplejoDeportivo + "','" + d.IdEstado + "');\">");
                    strHtml.Append("<img src='" + siteRoot + "/Contenido/Images/btn-edit.png' /></a>&nbsp;");
                    strHtml.Append("<a href='#' onclick=\"delete_('" + d.IdComplejoDeportivo + "');\">");
                    strHtml.Append("<img src='" + siteRoot + "/Contenido/Images/btn-cancel.png' /></a>");
                    strHtml.Append("</td>");
                    strHtml.Append("<td>" + d.ComplejoDeportivoDes + "</td>");
                    strHtml.Append("<td>" + d.SedeDes + "</td>");
                    strHtml.Append("<td>" + d.TipoComplejoDeportivoDes + "</td>");
                    strHtml.Append("<td>" + d.EstadoDes + "</td>");

                    strHtml.Append("</tr>");
                }

                strHtml.Append("</tbody>");
                #endregion
            }
            strHtml.Append("</table>");

            return strHtml.ToString();
        }
        public async Task<JsonResult> SaveComplejoDeportivo(int id, string complejo, int sede, int tipo, int estado)
        {
            var obj = new ComplejoDeportivoDTO()
            {
                IdComplejoDeportivo = id,
                ComplejoDeportivoDes = complejo,
                IdSede = sede,
                IdTipoComplejoDeportivo = tipo,
                IdEstado = estado
            };
            var json = new JsonResult();
            try
            {
                var datos = await new OlimpiadasServicios().SaveComplejoDeportivo(obj);

                var model = new Objetos();
                model.Count = 1;
                model.ListaSedes = await (new OlimpiadasServicios()).GetSedes();
                model.ListaTipoComplejosDeportivos = await (new OlimpiadasServicios()).GetTipoComplejosDeportivos();
                model.ListaEstados = (List<EstadosDTO>)Session[DatosSesion.SesionEstados];
                model.Htmlview = ListaComplejosHtml(datos);
                json = Json(model);
            }
            catch (Exception ex)
            {
            }

            return json;
        }
        public async Task<JsonResult> DeleteComplejoDeportivo(int id)
        {
            var json = new JsonResult();
            try
            {
                var datos = await new OlimpiadasServicios().DeleteComplejoDeportivo(id);

                var model = new Objetos();
                model.Count = 1;

Gestor.MVC/Controllers/DashboardsController.cs
using System.Web.Mvc;

namespace Gestor.MVC.Controllers
{
    public class DashboardsController : BaseController
    {
        public ActionResult Dashboard_1()
        {
            if (!this.IsValidSesion) return this.RedirectToLogin();
            else return RedirectToAction("Profile", "AppViews");
            //return View();
        }

        public ActionResult Dashboard_2()
        {
            return View();
        }

        public ActionResult Dashboard_3()
        {
            return View();
        }

        public ActionResult Dashboard_4()
        {
            return View();
        }

        public ActionResult Dashboard_4_1()
        {
            return View();
        }

        public ActionResult Dashboard_5()
        {
            return View();
        }

    }
}

Gestor.MVC/Views/Administracion/ComplejoDeportivo.cshtml
@{
    ViewBag.Title = "Prestamos";
}
<script type="text/javascript">
        var siteRoot = "@Url.Content("~/")";
</script>
<input type="hidden" id="page_" value="@Model.Pageview" />
<input type="hidden" id="id" value="0" />
<input type="hidden" id="hora" value="0" />
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Listado de Sedes</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard_1", "Dashboards")">Inicio</a>
            </li>
            <li class="active">
                <strong>Sedes</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<a class="dropdown-toggle" data-toggle="modal" data-target="#formulario" href="#" id="popupFrm"></a>
<div class="modal inmodal fade" id="formulario" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content animated fadeInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title">Complejo Deportivo</h3>
            </div>
            <div class="modal-body">
                <form role="form">
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Complejo Deportivo</label>
                        <div class="col-lg-6"><input type="text" id="fr_complejo" class="form-control" placeholder="Ingrese un nombre" autocomplete="off" /></div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Sede</label>
                        <div class="col-lg-6">
                            <select class="chosen-select form-control" id="fr_sede"></select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Tipo</label>
                        <div class="col-lg-6">
                            <select class="chosen-select form-control" id="fr_tipocomplejo"></select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Estado</label>
                        <div class="col-lg-6">
                            <select class="chosen-select form-control" id="fr_estado"></select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" id="idClose">Cerrar</button>
                <button type="button" class="btn btn-primary" id="idSave">Guardar</button>
            </div>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="ibox-tools">
                        <a class="dropdown-toggle" title="Agregar" onclick="add_()">
                            <img src="~/Contenido/Images/Plus.png" />
                        </a>
                    </div>
                </div>
                <div class='table-responsive' style="background-color:#ffffff">
                    <div class="ibox-content" id="lista1"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="fr_id" />
@section Styles {
    @Styles.Render("~/Contenido/plugins/dataTables/dataTablesStyles")
    @Styles.Render("~/Contenido/plugins/dropzone/dropZoneStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/Contenido/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/Contenido/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Contenido/plugins/blueimp/css/")
    @Styles.Render("~/Contenido/plugins/signature/signatureStyles")
    <link href="~/Contenido/bootstrap.css" rel="stylesheet" />
}
@section Scripts {
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/select2")
    @Scripts.Render("~/plugins/chosen")
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/typehead")
    @Scripts.Render("~/plugins/dropZone")
    @Scripts.Render("~/plugins/lightboxGallery")
    @Scripts.Render("~/plugins/signature")
    <script src="~/Scripts/plugins/chosen/chosen.jquery.js?v=1.0.1"></script>
    <script src="~/Scripts/plugins/dataTables/datatables.min.js?v=1.1"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script src="~/Contenido/Scripts/complejodeportivo.js?v=1.0.0"></script>
}

Gestor.MVC/Views/Administracion/Equipamientos.cshtml
@{
    ViewBag.Title = "Prestamos";
}
<script type="text/javascript">
        var siteRoot = "@Url.Content("~/")";
</script>
<input type="hidden" id="page_" value="@Model.Pageview" />
<input type="hidden" id="id" value="0" />
<input type="hidden" id="hora" value="0" />
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Listado de Equipamientos</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard_1", "Dashboards")">Inicio</a>
            </li>
            <li class="active">
                <strong>Equipamientos</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<a class="dropdown-toggle" data-toggle="modal" data-target="#formulario" href="#" id="popupFrm"></a>
<div class="modal inmodal fade" id="formulario" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content animated fadeInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title">Equipamiento</h3>
            </div>
            <div class="modal-body">
                <form role="form">
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Equipamiento</label>
                        <div class="col-lg-6"><input type="text" id="fr_equipamiento" class="form-control" placeholder="Ingrese un equipamiento" autocomplete="off" /></div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Estado</label>
                        <div class="col-lg-6">
                            <select class="chosen-select form-control" id="fr_estado"></select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal" id="idClose">Cerrar</button>
                <button type="button" class="btn btn-primary" id="idSave">Guardar</button>
            </div>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="ibox-tools">
                        <a class="dropdown-toggle" title="Agregar" onclick="add_()">
                            <img src="~/Contenido/Images/Plus.png" />
                        </a>
                    </div>
                </div>
                <div class='table-responsive' style="background-color:#ffffff">
                    <div class="ibox-content" id="lista1"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="fr_id" />
@section Styles {
    @Styles.Render("~/Contenido/plugins/dataTables/dataTablesStyles")
    @Styles.Render("~/Contenido/plugins/dropzone/dropZoneStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/Contenido/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/Contenido/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Contenido/plugins/blueimp/css/")
    @Styles.Render("~/Contenido/plugins/signature/signatureStyles")
    <link href="~/Contenido/bootstrap.css" rel="stylesheet" />
}
@section Scripts {
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/select2")
    @Scripts.Render("~/plugins/chosen")
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/typehead")
    @Scripts.Render("~/plugins/dropZone")
    @Scripts.Render("~/plugins/lightboxGallery")
    @Scripts.Render("~/plugins/signature")
    <script src="~/Scripts/plugins/chosen/chosen.jquery.js?v=1.0.1"></script>
    <script src="~/Scripts/plugins/dataTables/datatables.min.js?v=1.1"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script src="~/Contenido/Scripts/equipamientos.js?v=1.0.0"></script>
}

Gestor.MVC/Views/Administracion/Menu_old.cshtml
@model Gestor.MVC.Models.Objetos

@{
    ViewBag.Title = "Menu";
    var tienHijos = false;
}



<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Mantenimiento Menú</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard_1", "Dashboards")">Inicio</a>
            </li>
            <li class="active">
                <strong>Mantenimiento de barra de Menú</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<!--Carga Meús-->
<div class="wrapper wrapper-content  animated fadeInRight">
    <div class="row">
        <div class="col-md-4">
            <div id="nestable-menu">
                <button type="button" data-action="expand-all" class="btn btn-white btn-sm">Expandir</button>
                <button type="button" data-action="collapse-all" class="btn btn-white btn-sm">Comprimir</button>
            </div>
        </div>
    </div>
    <div class="row">
        
        <div class="col-lg-6">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Nestable custom theme list</h5>
                    <div class="ibox-tools">
                        <a class="dropdown-toggle" data-toggle="modal" data-target="#myModal" href="#" title="Agregar">
                            <img src="~/Contenido/Images/Plus.png" />
                        </a>
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>                      
                    </div>
                </div>
                <div class="ibox-content">
                    <p class="m-b-lg">
                        Each list you can customize by standard css styles. Each element is responsive so you can add to it any other element to improve functionality of list.
                    </p>
                    <div class="dd" id="nestable">
                        <ol class="dd-list">
                            
                            @foreach (var item in Model.ListaMenuPortalPadres)
                            {
                                tienHijos = false;
                                <li class="dd-item" data-id="@item.Menucodi">
                                    <div class="dd-handle">
                                        <span class="label label-info"><i class="fa fa-users"></i></span> @item.Menutitle
                                    </div>

                                                                                                
                                @foreach (var hijo in Model.ListaMenuPortalHijos)
                                    {
                                        if (hijo.Padrecodi == item.Menucodi)
                                        {
                                            tienHijos = true;
                                        }                                    
                                    }                                
                               
                                    @if (tienHijos)
                                    {
                                        <ol class="dd-list">
                                            @foreach (var hijo in Model.ListaMenuPortalHijos)
                                            {
                                                if (hijo.Padrecodi == item.Menucodi)
                                                {
                                                    <li class="dd-item" data-id="@hijo.Menucodi">
                                                        <div class="dd-handle">
                                                            <span class="pull-right"> @hijo.Menuurl </span>
                                                            <span class="label label-info"><i class="fa fa-cog"></i></span> @hijo.Menutitle
                                                        </div>
                                                    </li>
                                                }
                                                            
                                            }
                                        </ol>
                                    }                                                                                                  
                                </li>
                            }                                                     
                        </ol>
                    </div>
                    <div class="m-t-md">
                        <h5>Serialised Output</h5>
                    </div>
                    <textarea id="nestable-output" class="form-control"></textarea>

                </div>
            </div>
        </div>
    </div>
</div>




<!--Fin Carga Menús-->


<div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <i class="fa fa-laptop modal-icon"></i>
                <h4 class="modal-title">Registrar Elemento Menú</h4>
            </div>
            <div class="modal-body">
                <form role="form">
                    <div class="form-group"><label>Titulo</label> <input type="text" placeholder="Titulo del elemento menú" class="form-control"></div>
                    <div class="form-group"><label>Descripción</label> <input type="text" placeholder="Descripción Menu" class="form-control"></div>
                    <div class="form-group"><label>Menú URL</label> <input type="text" placeholder="Url del Menù" class="form-control"></div>
                    <div class="form-group"><label>Menu Padre</label> 
                        <select class="form-control m-b" name="cbpadres">
                            <option value="-1">-NINGUNO-</option>
                            @foreach (var item in Model.ListaMenuPortalPadres)
                            {
                                <option value="@item.Menucodi">@item.Menutitle</option>
                            }
                        </select>
                        
                   </div>
                    <div class="form-group"><label>Email</label> <input type="email" placeholder="Enter email" class="form-control"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="SaveData">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/Contenido/plugins/dataTables/dataTablesStyles")
}
@section Scripts {
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/nestable")
   <script src="~/Contenido/Scripts/menu.js"></script>
}